name: Publish payment-gateway-spi JAR

on:
  push:
    branches:
      - main
    paths:
      - 'payment-gateway-spi/**'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -f payment-gateway-spi/pom.xml clean package

      - name: Publish to Maven Central (OSSRH)
        run: |
          echo "$SIGNING_KEY" > private.key
          gpg --batch --import private.key
          mvn -B -f payment-gateway-spi/pom.xml deploy -P release --settings .github/maven-settings.xml
          rm -f private.key
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SIGNING_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Clean up
        run: rm -f .github/maven-settings.xml
